# Setup
title:                DeepISP
tagline:             'Description Must Read Papers on Deep Learning for the Image Signal Processor (ISP)'
description:         'A webpage dedicated to the latest research on Deep Learning for the Image Signal Processor (ISP).'
url:                 https://deepisp.github.io
baseurl:             ''
disqus:
  shortname: sjmoran
collections:
  publications:
    output: true
    permalink: /:collection/:path/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
